//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2021.03.15 at 10:17:38 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.webleaf.com/config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.webleaf.config;
