//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2021.03.15 at 10:17:38 AM IST 
//


package com.webleaf.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for webLeafConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webLeafConfig"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="command-configs" type="{http://www.webleaf.com/config}commandConfig" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "webLeafConfig", propOrder = {
    "commandConfigs"
})
public class WebLeafConfig {

    @XmlElement(name = "command-configs")
    protected CommandConfig commandConfigs;

    /**
     * Gets the value of the commandConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link CommandConfig }
     *     
     */
    public CommandConfig getCommandConfigs() {
        return commandConfigs;
    }

    /**
     * Sets the value of the commandConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandConfig }
     *     
     */
    public void setCommandConfigs(CommandConfig value) {
        this.commandConfigs = value;
    }

}
